package com.example.tacticore.ui.counter

object CounterRules {
    private val counters = mapOf(
        "Tracer" to listOf("Winston", "Mauga", "Symmetra", "Torbjorn", "Mei", "Brigitte", "Moira"),
        "Reinhardt" to listOf("Sombra", "Pharah", "Cassidy", "Zenyatta", "Mei"),
        "Mercy" to listOf("Genji", "Tracer", "Widowmaker", "Cassidy", "Echo", "Roadhoag", "Winston"),
        "Genji" to listOf("Winston", "Moira", "Ana", "Mei", "Symmetra", "Zarya"),
        "Winston" to listOf("Junkrat", "Bastion", "Zarya", "Pharah", "Ana", "Brigitte"),
        "D.va" to listOf("Zarya", "Winston", "Symmetra", "Bastion", "Sojourn", "Moira"),
        "Doomfist" to listOf("Sombra", "Tracer", "Bastion", "Genji", "Ana", "Brigitte"),
        "Junker Queen" to listOf("Wrecking ball", "Widowmaker", "Ana", "Lucio", "Kiriko"),
        "Mauga" to listOf("Doomfist", "Wrecking ball", "Mauga", "Sombra", "Zenyatta", "Kiriko"),
        "Orisa" to listOf("Zarya", "D.va", "Mei", "Echo", "Moira"),
        "Ramattra" to listOf("Roadhog", "Reaper", "Tracer", "Pharah", "Genji", "Cassidy", "Kiriko"),
        "Roadhog" to listOf("Wrecking ball", "Roadhog", "Reaper", "Echo", "Junkrat", "Ana"),
        "Sigma" to listOf("Ramattra", "Roadhog", "Genji", "Tracer", "Sombra", "Lucio"),
        "Wrecking ball" to listOf("Roadhog", "Doomfist", "Mei", "Sombra", "Ana", "Brigitte"),
        "Zarya" to listOf("D.va", "Hanzo", "Widowmaker", "Cassidy", "Tracer", "Zenyatta"),
        "Ashe" to listOf("Zarya", "Genji", "Tracer", "Widowmaker", "Ana", "Kiriko"),
        "Bastion" to listOf("Zarya", "Orisa", "Junkrat", "Pharah", "Genji", "Tracer", "Ana"),
        "Cassidy" to listOf("Reinhardt", "Winston", "Genji", "Cassidy", "Ana"),
        "Echo" to listOf("Winston", "Zarya", "Ashe", "Cassidy", "Soldier: 76", "Widowmaker"),
        "Hanzo" to listOf("D.va", "Wrecking ball", "Widowmaker", "Genji", "Lucio"),
        "Junkrat" to listOf("Zarya", "Wrecking ball", "Cassidy", "Soldier: 76", "Lucio", "Brigitte", "Lifeweaver"),
        "Mei" to listOf("D.va", "Sombra", "Pharah", "Echo", "Kiriko"),
        "Pharah" to listOf("D.va", "Soldier: 76", "Cassidy", "Ashe", "Widowmaker", "Ana"),
        "Reaper" to listOf("Zarya", "Pharah", "Echo", "Junkrat", "Widowmaker", "Ana"),
        "Sojourn" to listOf("Winston", "Mauga", "Genji", "Tracer", "Lucio"),
        "Soldier: 76" to listOf("Roadhog", "Ashe", "Cassidy", "Genji", "Junkrat", "Ana", "Lucio"),
        "Sombra" to listOf("Pharah", "Junkrat", "Hanzo", "Mei", "Kiriko", "Ana"),
        "Symmetra" to listOf("Winston", "Mauga", "Pharah", "Junkrat", "Echo"),
        "Torbjorn" to listOf("D.va", "Junkrat", "Ashe"),
        "Widowmaker" to listOf("D.va", "Winston", "Genji", "Tracer", "Sombra", "Zenyatta"),
        "Ana" to listOf("Winston", "Ramattra", "Echo", "Pharah", "Tracer", "Kiriko"),
        "Baptiste" to listOf("Cassidy", "Ashe", "Mei", "Lucio"),
        "Brigitte" to listOf("Pharah", "Echo", "Junkrat"),
        "Illari" to listOf("Orisa", "Zarya", "D.va", "Cassidy", "Ashe", "Widowmaker", "Baptiste", "Lifeweaver", "Lucio"),
        "Kiriko" to listOf("Roadhog", "Tracer", "Sombra", "Genji", "Mei"),
        "Lifeweaver" to listOf("Sombra", "Soldier: 76", "Lucio"),
        "Lucio" to listOf("Winston", "Roadhog", "Soldier: 76", "Cassidy", "Symmetra", "Torbjorn", "Mei", "Moira"),
        "Moira" to listOf("Roadhog", "Zarya", "Echo", "Pharah", "Widowmaker", "Junkrat", "Mei", "Ashe"),
        "Zenyatta" to listOf("Junkrat", "Pharah", "Cassidy", "Widowmaker", "Ashe", "Hanzo", "Tracer", "Kiriko", "Zenyatta"),
        "Anran" to listOf("Winston", "Sombra", "Kiriko", "Widowmaker"),
        "Domina" to listOf("Reaper", "Vendetta", "Mei", "Sombra", "Winston", "Moira"),
        "Hazard" to listOf("D.va", "Ana", "Orisa", "Sombra"),
        "Jetpack Cat" to listOf("Soldier: 76", "Cassidy", "Ashe", "Sombra"),
        "Juno" to listOf("Sombra", "Ashe", "Orisa"),
        "Mizuki" to listOf("Pharah", "Junkrat"),
        "Sierra" to listOf("Cassidy", "Soldier: 76", "Freja"),
        "Vendetta" to listOf("Cassidy", "Sigma"),
        "Venture" to listOf("Mei", "Sombra", "Pharah", "Echo"),
        "Wuyang" to listOf("D.va", "Winston"),
        "Emre" to listOf("D.va", "Sombra"),
        "Freja" to listOf("Cassidy", "Soldier: 76", "D.va")
    )

    fun getCountersForEnemy(enemyName: String): List<String> {
        return counters[enemyName] ?: emptyList()
    }
}